### ISSUE TITLE
Setup hosted documentation

### ISSUE THREAD

**Issue by mattBrzezinski** [JuliaCloud/AWSBatch.jl#3]
Attempted to do so in #2 , setup the Deploy Key and Secret, doesn't to ever write.

**Comment by mattBrzezinski** [comment]
When creating the keys, I ran:

```julia
DocumenterTools.genkeys(user="JuliaCloud", repo="git@github.com:JuliaCloud/AWSBatch.jl.git")
```

As per the documentation [here](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh)

**Comment by iamed2** [comment]
The docs/make.jl doesn't call `deploydocs`
